/**
 * Source adapter: OpenStreetMap science centers / museums / aquariums / zoos / planetariums (CC0),
 * generated by scripts/generate-osm-volunteering.ts -> supabase/seed/osm-volunteering.json. These
 * are real, visitable places a high-schooler can contact to volunteer or explore programs (the
 * "Discovery Cube" archetype), mapped to the `volunteer` kind.
 *
 * We don't know each org's specific volunteer policy, so `is_recruiting` stays false (no over-claim,
 * same discipline as the OpenAlex labs); `grade_min: 9` marks them high-school-relevant so they can
 * match HS students. Tags are canonical taxonomy labels set at generation time, so they match
 * student interests without re-running the classifier.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { truncate, type NormalizedListing } from "../mapping";

export interface OsmEntry {
  id: string;
  name: string;
  url: string | null;
  location_name: string | null;
  lat: number | null;
  lng: number | null;
  tags: string[];
}

const SOURCE_PATH = join(process.cwd(), "supabase", "seed", "osm-volunteering.json");

export function mapOsmEntry(e: OsmEntry): NormalizedListing {
  const where = e.location_name ? ` in ${e.location_name}` : "";
  return {
    external_id: e.id,
    source: "volunteering",
    kind: "volunteer",
    title: e.name.trim(),
    slug: e.id,
    url: e.url,
    short_description: truncate(`Science center / museum${where} — visit or reach out about student volunteering and programs.`, 300),
    long_description: null,
    location_name: e.location_name,
    is_remote: false,
    team_size: null,
    industry: "Volunteering",
    subindustry: null,
    cost_type: "free",
    is_recruiting: false,
    badges: ["osm", "volunteer"],
    status: "approved",
    grade_min: 9,
    grade_max: null,
    age_min: null,
    deadline: null,
    tag_labels: (e.tags ?? []).map((t) => t.trim()).filter(Boolean),
  };
}

export function loadOsmVolunteerListings(): NormalizedListing[] {
  try {
    const data = JSON.parse(readFileSync(SOURCE_PATH, "utf8")) as OsmEntry[];
    if (!Array.isArray(data)) return [];
    return data.map(mapOsmEntry);
  } catch {
    return []; // snapshot not generated yet — no-op
  }
}
